name: box4kids-frontend

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    command: yarn serve -s build -l 3000
