/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Box4Kids
 * API для Box4Kids - сервис аренды игрушек для детей
 * OpenAPI spec version: 0.1.0
 */

/**
 * Схема ответа при создании пакетного платежа
 */
export interface BatchPaymentResponse {
  payment_id: number;
  external_payment_id: string;
  payment_url: string;
  amount: number;
  currency: string;
  subscription_count: number;
  message: string;
}
