/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Box4Kids
 * API для Box4Kids - сервис аренды игрушек для детей
 * OpenAPI spec version: 0.1.0
 */

/**
 * Схема для создания пакетного платежа
 */
export interface BatchPaymentCreateRequest {
  subscription_ids: number[];
}
