/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Box4Kids
 * API для Box4Kids - сервис аренды игрушек для детей
 * OpenAPI spec version: 0.1.0
 */
import type { ChildWithBoxesResponseComment } from './childWithBoxesResponseComment';
import type { ChildWithBoxesResponseCurrentBox } from './childWithBoxesResponseCurrentBox';
import type { ChildWithBoxesResponseNextBox } from './childWithBoxesResponseNextBox';

/**
 * Схема для ребенка с наборами
 */
export interface ChildWithBoxesResponse {
  id: number;
  name: string;
  date_of_birth: string;
  gender: string;
  has_limitations: boolean;
  comment?: ChildWithBoxesResponseComment;
  current_box?: ChildWithBoxesResponseCurrentBox;
  next_box?: ChildWithBoxesResponseNextBox;
}
