/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Box4Kids
 * API для Box4Kids - сервис аренды игрушек для детей
 * OpenAPI spec version: 0.1.0
 */
import type { Gender } from './gender';
import type { ChildCreateComment } from './childCreateComment';

export interface ChildCreate {
  /** Имя ребенка */
  name: string;
  /** Дата рождения ребенка */
  date_of_birth: string;
  /** Пол ребенка */
  gender: Gender;
  /** Есть ли ограничения по здоровью */
  has_limitations?: boolean;
  /** Комментарий о ребенке */
  comment?: ChildCreateComment;
}
