/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Box4Kids
 * API для Box4Kids - сервис аренды игрушек для детей
 * OpenAPI spec version: 0.1.0
 */
import type { ChildUpdateName } from './childUpdateName';
import type { ChildUpdateDateOfBirth } from './childUpdateDateOfBirth';
import type { ChildUpdateGender } from './childUpdateGender';
import type { ChildUpdateHasLimitations } from './childUpdateHasLimitations';
import type { ChildUpdateComment } from './childUpdateComment';
import type { ChildUpdateInterestIds } from './childUpdateInterestIds';
import type { ChildUpdateSkillIds } from './childUpdateSkillIds';

export interface ChildUpdate {
  name?: ChildUpdateName;
  date_of_birth?: ChildUpdateDateOfBirth;
  gender?: ChildUpdateGender;
  has_limitations?: ChildUpdateHasLimitations;
  comment?: ChildUpdateComment;
  interest_ids?: ChildUpdateInterestIds;
  skill_ids?: ChildUpdateSkillIds;
}
