/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Box4Kids
 * API для Box4Kids - сервис аренды игрушек для детей
 * OpenAPI spec version: 0.1.0
 */

export interface ConfirmPhoneChangeRequest {
  /** Новый номер телефона */
  new_phone: string;
  /** OTP код для нового номера */
  new_phone_code: string;
}
