/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Box4Kids
 * API для Box4Kids - сервис аренды игрушек для детей
 * OpenAPI spec version: 0.1.0
 */
import type { DeliveryInfoUpdateName } from './deliveryInfoUpdateName';
import type { DeliveryInfoUpdateAddress } from './deliveryInfoUpdateAddress';
import type { DeliveryInfoUpdateDate } from './deliveryInfoUpdateDate';
import type { DeliveryInfoUpdateTime } from './deliveryInfoUpdateTime';
import type { DeliveryInfoUpdateCourierComment } from './deliveryInfoUpdateCourierComment';

/**
 * Схема для обновления адреса доставки
 */
export interface DeliveryInfoUpdate {
  /** Название адреса */
  name?: DeliveryInfoUpdateName;
  /** Полный адрес доставки */
  address?: DeliveryInfoUpdateAddress;
  /** Дата доставки */
  date?: DeliveryInfoUpdateDate;
  /** Предпочтительное время доставки */
  time?: DeliveryInfoUpdateTime;
  /** Комментарий для курьера */
  courier_comment?: DeliveryInfoUpdateCourierComment;
}
