/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Box4Kids
 * API для Box4Kids - сервис аренды игрушек для детей
 * OpenAPI spec version: 0.1.0
 */
import type { DeliveryInfoCreateDeliveryTimePreference } from './deliveryInfoCreateDeliveryTimePreference';
import type { DeliveryInfoCreateCourierComment } from './deliveryInfoCreateCourierComment';

/**
 * Схема для создания нового адреса доставки
 */
export interface DeliveryInfoCreate {
  /** Название адреса (Дом, Работа, и т.д.) */
  name: string;
  /** Полный адрес доставки */
  address: string;
  /** Предпочтительное время доставки */
  delivery_time_preference?: DeliveryInfoCreateDeliveryTimePreference;
  /** Комментарий для курьера */
  courier_comment?: DeliveryInfoCreateCourierComment;
}
