/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Box4Kids
 * API для Box4Kids - сервис аренды игрушек для детей
 * OpenAPI spec version: 0.1.0
 */
import type { DeliveryInfoResponseDeliveryTimePreference } from './deliveryInfoResponseDeliveryTimePreference';
import type { DeliveryInfoResponseCourierComment } from './deliveryInfoResponseCourierComment';

/**
 * Схема ответа с данными адреса доставки
 */
export interface DeliveryInfoResponse {
  /** Название адреса (Дом, Работа, и т.д.) */
  name: string;
  /** Полный адрес доставки */
  address: string;
  /** Предпочтительное время доставки */
  delivery_time_preference?: DeliveryInfoResponseDeliveryTimePreference;
  /** Комментарий для курьера */
  courier_comment?: DeliveryInfoResponseCourierComment;
  id: number;
  user_id: number;
  created_at: string;
}
