/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Box4Kids
 * API для Box4Kids - сервис аренды игрушек для детей
 * OpenAPI spec version: 0.1.0
 */

export interface InitiatePhoneChangeRequest {
  /** OTP код для текущего номера */
  current_phone_code: string;
  /** Новый номер телефона */
  new_phone: string;
}
