/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Box4Kids
 * API для Box4Kids - сервис аренды игрушек для детей
 * OpenAPI spec version: 0.1.0
 */
import type { NextBoxItemResponse } from './nextBoxItemResponse';
import type { NextBoxResponseDeliveryDate } from './nextBoxResponseDeliveryDate';
import type { NextBoxResponseReturnDate } from './nextBoxResponseReturnDate';
import type { NextBoxResponseDeliveryTime } from './nextBoxResponseDeliveryTime';
import type { NextBoxResponseReturnTime } from './nextBoxResponseReturnTime';

/**
 * Следующий набор (генерируется на лету)
 */
export interface NextBoxResponse {
  items: NextBoxItemResponse[];
  delivery_date?: NextBoxResponseDeliveryDate;
  return_date?: NextBoxResponseReturnDate;
  delivery_time?: NextBoxResponseDeliveryTime;
  return_time?: NextBoxResponseReturnTime;
  message: string;
}
