/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Box4Kids
 * API для Box4Kids - сервис аренды игрушек для детей
 * OpenAPI spec version: 0.1.0
 */

/**
 * Статусы платежа
 */
export type PaymentStatusEnum = typeof PaymentStatusEnum[keyof typeof PaymentStatusEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentStatusEnum = {
  success: 'success',
  failed: 'failed',
} as const;
