/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Box4Kids
 * API для Box4Kids - сервис аренды игрушек для детей
 * OpenAPI spec version: 0.1.0
 */
import type { SubscriptionResponseDeliveryInfoId } from './subscriptionResponseDeliveryInfoId';
import type { SubscriptionStatus } from './subscriptionStatus';
import type { SubscriptionResponseExpiresAt } from './subscriptionResponseExpiresAt';

/**
 * Схема ответа с данными подписки
 */
export interface SubscriptionResponse {
  id: number;
  child_id: number;
  plan_id: number;
  delivery_info_id: SubscriptionResponseDeliveryInfoId;
  status: SubscriptionStatus;
  discount_percent: number;
  created_at: string;
  expires_at: SubscriptionResponseExpiresAt;
}
