/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Box4Kids
 * API для Box4Kids - сервис аренды игрушек для детей
 * OpenAPI spec version: 0.1.0
 */
import type { SubscriptionCreateRequestDeliveryInfoId } from './subscriptionCreateRequestDeliveryInfoId';

/**
 * Схема для создания подписки
 */
export interface SubscriptionCreateRequest {
  /** ID ребенка */
  child_id: number;
  /** ID плана подписки */
  plan_id: number;
  /** ID адреса доставки */
  delivery_info_id?: SubscriptionCreateRequestDeliveryInfoId;
}
