/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Box4Kids
 * API для Box4Kids - сервис аренды игрушек для детей
 * OpenAPI spec version: 0.1.0
 */
import type { SubscriptionPlanResponseDescription } from './subscriptionPlanResponseDescription';
import type { ToyCategoryConfigResponse } from './toyCategoryConfigResponse';

/**
 * Ответ с планом подписки
 */
export interface SubscriptionPlanResponse {
  id: number;
  name: string;
  price_monthly: number;
  toy_count: number;
  description?: SubscriptionPlanResponseDescription;
  toy_configurations?: ToyCategoryConfigResponse[];
}
