/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Box4Kids
 * API для Box4Kids - сервис аренды игрушек для детей
 * OpenAPI spec version: 0.1.0
 */
import type { SubscriptionUpdateRequestChildId } from './subscriptionUpdateRequestChildId';
import type { SubscriptionUpdateRequestPlanId } from './subscriptionUpdateRequestPlanId';
import type { SubscriptionUpdateRequestDeliveryInfoId } from './subscriptionUpdateRequestDeliveryInfoId';
import type { SubscriptionUpdateRequestStatus } from './subscriptionUpdateRequestStatus';
import type { SubscriptionUpdateRequestDiscountPercent } from './subscriptionUpdateRequestDiscountPercent';
import type { SubscriptionUpdateRequestExpiresAt } from './subscriptionUpdateRequestExpiresAt';

/**
 * Схема для обновления подписки
 */
export interface SubscriptionUpdateRequest {
  /** ID ребенка */
  child_id?: SubscriptionUpdateRequestChildId;
  /** ID плана подписки */
  plan_id?: SubscriptionUpdateRequestPlanId;
  /** ID адреса доставки */
  delivery_info_id?: SubscriptionUpdateRequestDeliveryInfoId;
  /** Статус подписки */
  status?: SubscriptionUpdateRequestStatus;
  /** Процент скидки */
  discount_percent?: SubscriptionUpdateRequestDiscountPercent;
  /** Дата истечения */
  expires_at?: SubscriptionUpdateRequestExpiresAt;
}
