/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Box4Kids
 * API для Box4Kids - сервис аренды игрушек для детей
 * OpenAPI spec version: 0.1.0
 */
import type { SubscriptionWithDetailsResponseDeliveryInfoId } from './subscriptionWithDetailsResponseDeliveryInfoId';
import type { SubscriptionStatus } from './subscriptionStatus';
import type { SubscriptionWithDetailsResponseExpiresAt } from './subscriptionWithDetailsResponseExpiresAt';
import type { SubscriptionWithDetailsResponseUserName } from './subscriptionWithDetailsResponseUserName';

/**
 * Схема ответа с подробными данными подписки
 */
export interface SubscriptionWithDetailsResponse {
  id: number;
  child_id: number;
  plan_id: number;
  delivery_info_id: SubscriptionWithDetailsResponseDeliveryInfoId;
  status: SubscriptionStatus;
  discount_percent: number;
  created_at: string;
  expires_at: SubscriptionWithDetailsResponseExpiresAt;
  child_name: string;
  plan_name: string;
  plan_price: number;
  user_id: number;
  user_name: SubscriptionWithDetailsResponseUserName;
}
