/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Box4Kids
 * API для Box4Kids - сервис аренды игрушек для детей
 * OpenAPI spec version: 0.1.0
 */
import type { ToyBoxReviewResponseComment } from './toyBoxReviewResponseComment';

/**
 * Отзыв на набор
 */
export interface ToyBoxReviewResponse {
  id: number;
  user_id: number;
  rating: number;
  comment?: ToyBoxReviewResponseComment;
  created_at: string;
}
