/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Box4Kids
 * API для Box4Kids - сервис аренды игрушек для детей
 * OpenAPI spec version: 0.1.0
 */
import type { ToyBoxReviewRequestComment } from './toyBoxReviewRequestComment';

/**
 * Запрос на добавление отзыва
 */
export interface ToyBoxReviewRequest {
  /** ID пользователя оставляющего отзыв */
  user_id: number;
  /**
   * Оценка от 1 до 5
   * @minimum 1
   * @maximum 5
   */
  rating: number;
  /** Комментарий к отзыву */
  comment?: ToyBoxReviewRequestComment;
}
