/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Box4Kids
 * API для Box4Kids - сервис аренды игрушек для детей
 * OpenAPI spec version: 0.1.0
 */
import type { ToyBoxResponseDeliveryInfoId } from './toyBoxResponseDeliveryInfoId';
import type { ToyBoxStatus } from './toyBoxStatus';
import type { ToyBoxResponseDeliveryDate } from './toyBoxResponseDeliveryDate';
import type { ToyBoxResponseReturnDate } from './toyBoxResponseReturnDate';
import type { ToyBoxItemResponse } from './toyBoxItemResponse';
import type { ToyBoxReviewResponse } from './toyBoxReviewResponse';

/**
 * Ответ с набором игрушек
 */
export interface ToyBoxResponse {
  id: number;
  subscription_id: number;
  child_id: number;
  delivery_info_id?: ToyBoxResponseDeliveryInfoId;
  status: ToyBoxStatus;
  delivery_date?: ToyBoxResponseDeliveryDate;
  return_date?: ToyBoxResponseReturnDate;
  created_at: string;
  items?: ToyBoxItemResponse[];
  reviews?: ToyBoxReviewResponse[];
}
