/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Box4Kids
 * API для Box4Kids - сервис аренды игрушек для детей
 * OpenAPI spec version: 0.1.0
 */

/**
 * Статусы набора игрушек в процессе аренды
 */
export type ToyBoxStatus = typeof ToyBoxStatus[keyof typeof ToyBoxStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ToyBoxStatus = {
  planned: 'planned',
  assembled: 'assembled',
  shipped: 'shipped',
  delivered: 'delivered',
  returned: 'returned',
} as const;
