/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Box4Kids
 * API для Box4Kids - сервис аренды игрушек для детей
 * OpenAPI spec version: 0.1.0
 */
import type { ToyCategoryConfigResponseDescription } from './toyCategoryConfigResponseDescription';
import type { ToyCategoryConfigResponseIcon } from './toyCategoryConfigResponseIcon';

/**
 * Конфигурация категории игрушек в плане
 */
export interface ToyCategoryConfigResponse {
  id: number;
  name: string;
  description?: ToyCategoryConfigResponseDescription;
  icon?: ToyCategoryConfigResponseIcon;
  quantity: number;
}
